[project]
name = "cmk-crypto"
version = "1.1.0"
dynamic = ["dependencies"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.package-data]
"cmk.crypto" = ["py.typed"]

[tool.bandit]
