# Options below are to provide static linking
[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = [
  "-C",
  "target-feature=+crt-static",
  "-C",
  "link-args=/DEFAULTLIB:libucrt.lib /DEFAULTLIB:libvcruntime.lib /DEFAULTLIB:libcmt.lib  /DEFAULTLIB:msvcrt.lib  /DEFAULTLIB:ucrt.lib",
  "-C",
  "link-args=/NODEFAULTLIB:libvcruntimed.lib /NODEFAULTLIB:vcruntime.lib /NODEFAULTLIB:vcruntimed.lib",
  "-C",
  "link-args=/NODEFAULTLIB:libcmtd.lib /NODEFAULTLIB:msvcrt.lib /NODEFAULTLIB:msvcrtd.lib",
  "-C",
  "link-args=/NODEFAULTLIB:ucrt.lib /NODEFAULTLIB:libucrtd.lib /NODEFAULTLIB:ucrtd.lib",
]

[env]
# Disable assert()s in C/C++ parts (e.g. wepoll-ffi), they map to _assert()/_wassert(),
# which is not provided by libucrt. The latter is needed for static linking.
# https://github.com/rust-lang/cc-rs#external-configuration-via-environment-variables
# set for all OS for simplicity
CFLAGS = "-DNDEBUG"
